pipeline {
    agent any
    
    tools {
        maven 'Maven 3.9.5'
        jdk 'JDK 17'
    }
    
    stages {
        stage('代码检查') {
            steps {
                sh 'mvn clean compile checkstyle:check'
            }
        }
        
        stage('构建服务') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        
        stage('运行测试') {
            steps {
                sh 'mvn test'
            }
        }
        
        stage('构建Docker镜像') {
            steps {
                sh 'docker-compose build'
            }
        }
        
        stage('部署服务') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
    
    post {
        success {
            echo '构建和部署成功！'
        }
        failure {
            echo '构建或部署失败！'
        }
    }
}