pipeline {
    agent any
    
    stages {
        stage('测试阶段') {
            steps {
                echo 'Hello, Jenkins!'
            }
        }
        
        stage('构建服务') {
            steps {
                echo 'Building services...'
            }
        }
        
        stage('部署服务') {
            steps {
                echo 'Deploying services...'
            }
        }
    }
    
    post {
        success {
            echo '构建和部署成功！'
        }
        failure {
            echo '构建或部署失败！'
        }
    }
}